### ISSUE TITLE
Is This Still Supported?

### ISSUE THREAD

**Issue by antmarakis** [aimacode/aima-csharp#2]
Hello. Is this still alive? I would like to try my hand at helping out.

It seems to be built like a C# solution (maybe for Visual Studio), but I don't understand why. Wouldn't it be best if we built this like the other repos (Python, for example) where we wrote is plain .cs files? It would be simpler that way.

**Comment by redblobgames** [comment]
I don't think anyone's actively working on the csharp repository. I agree though that it would be better to have plain cs files that can be used anywhere without IDE-specific files (Visual Studio or Unity etc.)

**Comment by ShobhitLamba** [comment]
Hello. 
Yes this repo is still alive. Though I have not worked on it for a while now due to other commitments. And anyone can contribute to the repository. Just put in a pull request.

And yes, this has been built like a C# project on Visual Studio, like Aima-Java and not like the python repo, simply because of my preference (sorry about that) to do that and since I was the only one contributing to the project, it was not a problem till now. But it is not that big an issue and worked well for Java till now.

You are welcome to make contributions to the project. There are some bugs in the code right now. I suggest you can start with debugging them and moving on with adding new code. There is also a Read me to write, an index to add, and other documentation which I was not able to add (I was the only one working sooo..)

Thank you for your interest.

**Comment by sfsharapov** [comment]
Hello.
I've added ReadMe, index and Contributing.md in my pull request. Could you revise it?
